# https://taskfile.dev

version: "3"

tasks:
  uv:
    cmds:
      - uv sync

  lint:
    cmds:
      - uv run ruff check

  scheduler:
    dir: app
    cmds:
      - uv run fastapi dev scheduler.py

  test:
    dir: app
    cmds:
      - task: lint
      - uv run pytest -s --pdb
