# https://taskfile.dev

version: "3"

tasks:
  uv:
    cmds:
      - uv sync

  lint:
    cmds:
      - uv run ruff check

  scheduler:
    dir: app
    cmds:
      - uv run fastapi dev scheduler.py

  test:
    cmds:
      - task: lint
      - uv run pytest --cov=app --cov-report=html --cov-report=term-missing -s --pdb ./tests
